//used to dummy data
import { Food } from "./app/shared/model/food";
export const sample_foods:Food[]=[
    {
    id: '1',
    name: 'Chicken Biryani',
    cookTime: '10-20 min',
    price: 50,
    favourite: true,
    //origin:  'Sangli',
    stars: 4.5,
    imageUrl: '/assets/chicken.jpg',
    tags: ['Lunch'],
  },
  {
    id: '2',
    name: 'Egg Biryani',
    cookTime: '10-20 min',
    price: 20,
    favourite: false,
    //origins:  'Islampur',
    stars: 3.5,
    imageUrl: '/assets/egg.jpeg',
    tags: ['Lunch'],
  },
  {
    id: '3',
    name: 'Hyderabadi Dum Biryani',
    cookTime: '20-30 min',
    price: 80,
    favourite: true,
    //origins:  'Hyderabad',
    stars: 5,
    imageUrl: '/assets/hyderabad.jpeg',
    tags: ['Lunch'],
  },
  {
    id: '4',
    name: 'Veg Pulav',
    cookTime: '20-30 min',
    price: 60,
    favourite: false,
    //origins:  'Pandharpur',
    stars: 4.5,
    imageUrl: '/assets/veg.jpeg',
    tags: ['Fast Food','Lunch'],
  },
  {
    id: '5',
    name: 'Culcatta Biryani',
    cookTime: '20-30 min',
    price: 70,
    favourite: false,
    //origins:  'Kolkata',
    stars: 4.5,
    imageUrl: '/assets/kolkata.jpg',
    tags: ['Lunch'],
  },
  {
    id: '6',
    name: 'Malabar Special',
    cookTime: '20-40 min',
    price: 60,
    favourite: false,
   // origins:  'Kolhapur',
    stars: 4.0,
    imageUrl: '/assets/malabar.jpg',
    tags: ['Lunch'],
  },
  {
    id: '7',
    name: 'Mutton Biryani',
    cookTime: '40-50 min',
    price: 90,
    favourite: false,
   // origins:  'Goa',
    stars: 5,
    imageUrl: '/assets/mutton.jpeg',
    tags: ['Lunch'],
  },
  {
    id: '8',
    name: 'Sindhi Biryani',
    cookTime: '30-40 min',
    price: 50,
    favourite: false,
   // origins:  'Gujarat',
    stars: 4.0,
    imageUrl: '/assets/sindhi.jpg',
    tags: ['Lunch'],
  },
  {
    id: '9',
    name: 'Fish Biryani',
    cookTime: '20-30 min',
    price: 70,
    favourite: true,
    //origins:  'Kolkata',
    stars: 4.5,
    imageUrl: '/assets/fish.jpg',
    tags: ['Lunch'],
  }
]